# Generated by Django 4.1 on 2022-08-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6)),
                ('grupo', models.CharField(max_length=4)),
                ('asesor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[(1, 'Obligatoria'), (2, 'Opcional')], max_length=1)),
                ('semestre', models.PositiveSmallIntegerField()),
                ('puntos', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.PositiveSmallIntegerField()),
                ('actividad', models.CharField(max_length=2)),
                ('f_inicio', models.DateField(editable=False)),
                ('f_entrega', models.DateField()),
                ('desc', models.TextField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clase_tarea', to='kardex.clase')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_clase', to='kardex.materia'),
        ),
    ]
